version: '3.7'
services:
    nginx:
        image: nginx
        container_name: nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./nginx.conf:/etc/nginx/nginx.conf
        command: /bin/bash -c "exec nginx -g 'daemon off;'"
        depends_on:
            - code-education-api
    
    mysql:
        container_name: mysql
        image: mysql:5.7.31
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root 
        volumes:
            - ./db/mysql:/var/lib/mysql

    code-education-api:
        image: node:15
        container_name: code-education-api
        volumes:
            - ./:/usr/src/app
        ports:
            - "8080:3000"
        depends_on:
            - mysql
        command: bash -c "cd /usr/src/app && npm i && npm start"